import {
  Flex,
  Heading,
  Text,
  useColorMode,
  Box,
  IconButton,
} from "@chakra-ui/react";
import Head from "next/head";
import { MoonStars, Sun } from "phosphor-react";

import AboutMe from "../components/AboutMe";

export default function Home() {
  const { colorMode, toggleColorMode } = useColorMode();
  return (
    <Box>
      <Flex
        as="nav"
        align="center"
        justify="space-between"
        padding={6}
        color="white"
        borderBottomWidth={1}
        _dark={{ borderBottomWidth: 0 }}
      >
        <Head>
          <title>Mason Schafer | Developer</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Flex align="center" mr={5} alignItems="center">
          <Heading
            as="h1"
            size="lg"
            bgGradient="linear(to-l, orange.300, orange.400)"
            bgClip={"text"}
            letterSpacing="tighter"
          >
            Mason Schafer
          </Heading>
          <Text
            ml="2"
            px="2"
            borderRadius="xl"
            bgGradient="linear(to-l, orange.300, orange.400)"
            color="white"
            fontWeight="bold"
            fontSize="sm"
          >
            always learning
          </Text>
        </Flex>

        <Box display="flex" alignItems="center" justifyContent="center">
          <IconButton
            aria-label="Make Dark Mode"
            variant={"ghost"}
            display={{ base: "none", md: "flex" }}
            borderRadius="full"
            mr="0.3rem"
            onClick={toggleColorMode}
            color="orange.400"
            icon={
              colorMode === "light" ? (
                <MoonStars size={19} weight="bold" />
              ) : (
                <Sun size={19} weight="bold" />
              )
            }
          />
        </Box>
      </Flex>
      <AboutMe />
    </Box>
  );
}
